### ISSUE TITLE
Documentation seems to parsing schema wrong

### ISSUE THREAD

**Issue by zwrawr** [JackoRo/SWEngPWS#8]
![image](https://user-images.githubusercontent.com/18352787/36215199-5b06a906-11a3-11e8-96a2-d1571886a944.png)

None of these are the correct attributes for the presentation element

**Comment by laurenkt** [comment]
Oh dear.

I just found an example XSLT for displaying XSD schemas just so that we could get the HTML docs on-line so we had a canonical URL but I didn't really tweak the transformation other than to display the title properly. Clearly it needs some work haha.

I can take a look at resolving the elements properly tonight if others can flesh out the documentation annotations in the document some more.

**Comment by laurenkt** [comment]
I've removed the spurious attributes in 1921af5c6d380d5ef50d4771c8000120ad98b7f0 but will amend so that it also looks up the relevant attribute groups.

**Comment by laurenkt** [comment]
Also added attribute groups, will close this now although I'm sure there will be further improvements, it's not really critical to agreeing the PWS standard on Thurs.
